spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.data: DEBUG

server:
  port: 8080

# Spring Boot Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      show-components: always
  health:
    defaults:
      enabled: true
