spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ringgo
    username: root
    password: 12345678

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ringgo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # Redis
  data:
    redis:
      host: localhost
      port: 6379

swagger:
  server:
    url: http://localhost:8080
    description: Local Server