spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.data: DEBUG

server:
  port: 8080
  forward-headers-strategy: framework

# SpringDoc OpenAPI 설정
springdoc:
  swagger-ui:
    path: /api
    config-url: /api/v3/api-docs/swagger-config
    url: /api/v3/api-docs
  api-docs:
    path: /api/v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Spring Boot Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      show-components: always
  health:
    defaults:
      enabled: true
