name: Deploy to NCP Server

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push가 발생하면 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
        
    - name: Deploy to NCP Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NCP_SERVER_IP }}
        username: ${{ secrets.NCP_SERVER_USERNAME }}
        key: ${{ secrets.NCP_SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          docker stop $(docker ps -q --filter ancestor=${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest) || true
          docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
